In [28]:
import os
motto = open("motto.txt", "w")
motto.write("Fiat Lux!")
motto.close()
motto = open("motto.txt", "r")
for line in motto:
    print(line)
motto.close()
motto = open("motto.txt", "a")
motto.write("\nLet there be light!")
motto.close()


Fiat Lux!


In [34]:
from matplotlib import image, pyplot
import os
path = os.path.dirname(os.path.abspath(__file__))
filename = path + '/' + 'lenna.bmp'
data = image.imread(filename)

NameError: name '__file__' is not defined

In [ ]:
import PyPDF2
file_handle = open(‘Sense-and-Sensibility-by-Jane-Austen.pdf’, ‘rb’) 
pdfReader = PyPDF2.PdfReader(file_handle) 
page_number = len(pdfReader.pages)   # this tells you total pages 
page_object = pdfReader.pages[0]    # We just get page 0 as example 
page_text = page_object.extractText()   # this is the str type of full p

In [41]:
import numpy as np

a = np.array([[6, -9, 1], [4, 24, 8]])
print(2 * a)

b = np.eye(2)
print(b@a)

c = np.array([[4, 3], [3, 2]])
d = np.array([[-4, 3], [3, -2]])
print(c@d)

[[ 12 -18   2]
 [  8  48  16]]
[[ 6. -9.  1.]
 [ 4. 24.  8.]]
[[-7  6]
 [-6  5]]


In [1]:
import numpy as np

a = np.array([[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]])
print(a[:, 1])
print(a[1, range(2, 4)])
print(a[2:4, 4:])


[ 1 11 21 31 41 51]
[12 13]
[[24 25]
 [34 35]]


In [ ]:
import numpy as np
def set_array(l, rows, cols, order)
    if order == "rows":
        a = np.reshape(l, rows, cols)
    elif order == "cols":
        a = np.reshape

In [7]:
## This is course material for Introduction to Python Scientific Programming
## Example code: matplotlib_clock.py
## Author: Allen Y. Yang
##
## (c) Copyright 2020. Intelligent Racing Inc. Not permitted for commercial use

from datetime import datetime
import matplotlib.pyplot as plt
import os
import numpy as np

# Initialization, define some constant
path = os.path.dirname(os.path.abspath(__file__))
filename = path + '/airplane.bmp'
background = plt.imread(filename)

second_hand_length = 200
second_hand_width = 2
minute_hand_length = 150
minute_hand_width = 6
hour_hand_length = 100
hour_hand_width = 10
center = np.array([256, 256])

def clock_hand_vector(angle, length):
    return np.array([length * np.sin(angle), -length * np.cos(angle)])

# draw an image background
fig, ax = plt.subplots()

while True:
    plt.imshow(background)

    # First retrieve the time
    now_time = datetime.now()
    hour = now_time.hour
    if hour>12: hour = hour - 12
    minute = now_time.minute
    second = now_time.second

    # Calculate end points of hour, minute, second

    hour_vector = clock_hand_vector(hour/12*2*np.pi, hour_hand_length)
    minute_vector = clock_hand_vector(minute/60*2*np.pi, minute_hand_length)
    second_vector = clock_hand_vector(second/60*2*np.pi, second_hand_length)

    plt.arrow(center[0], center[1], hour_vector[0], hour_vector[1], head_length = 3, linewidth = hour_hand_width, color = 'black')
    plt.arrow(center[0], center[1], minute_vector[0], minute_vector[1], linewidth = minute_hand_width, color = 'black')
    plt.arrow(center[0], center[1], second_vector[0], second_vector[1], linewidth = second_hand_width, color = 'red')

    plt.pause(0.1)
    plt.clf()


NameError: name '__file__' is not defined